sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.env .

script:
  - docker run docker-react yarn test --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-724283824249"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"